import { Inter } from "next/font/google";
// import "./globals.css";
import { ChatAppProvider } from "@/context/ChatAppContext";
const inter = Inter({ subsets: ["latin"] });
import { NavBar } from "@/components";
export const metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({children }) {
  return (
    <html lang="en">
      <body>
      <ChatAppProvider>
      <NavBar/>
      {children}
      </ChatAppProvider>
      </body>
    </html>
    
  );
}
