import { Inter } from "next/font/google";
import "./globals.css";
import { ChatAppProvider } from "@/context/ChatAppContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ChatAppProvider>
    <html lang="en">
    
      <body className={inter.className}>{children}</body>
    </html>
    </ChatAppProvider>
  );
}
